services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Markup\ElasticsearchBundle\:
        resource: '../../*'

    Markup\ElasticsearchBundle\Controller\:
        resource: '../../Controller/'
        tags: [controller.service_arguments]

    Markup\ElasticsearchBundle\ServiceLocator:
        tags: [container.service_locator]

    Markup\ElasticsearchBundle\Twig\KibanaLinkExtension:
        autowire: true
        autoconfigure: false
